name: CI Docker Image PokeWEB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -name: dokcer login
    environment:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Building PokeWEB Docker Image
      run: docker build . --file Dockerfile --tag pokeweb:$(date +%s)
