name: CI Docker Image PokeWEB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building PokeWEB Docker Image
      run: docker build . --file Dockerfile --tag pokeweb:$(date +%s)
